### ISSUE TITLE
Compiling for Windows Arm has errors

### ISSUE THREAD

**Issue by srfraser** [go-ole/go-ole#202]
Discussed in https://github.com/shirou/gopsutil/issues/916 the contents of variant_386.go and variant_date_386.go copied to variant_arm.go and variant_date_arm.go (with the build directives updated) seems to work

```
$ GOOS=windows GOARCH=arm go build .
# github.com/go-ole/go-ole
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/com.go:238:21: undefined: VARIANT
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/com.go:247:22: undefined: VARIANT
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/connect.go:79:72: undefined: VARIANT
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/connect.go:90:76: undefined: VARIANT
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/connect.go:105:69: undefined: VARIANT
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/connect.go:115:73: undefined: VARIANT
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/connect.go:129:69: undefined: VARIANT
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/connect.go:139:73: undefined: VARIANT
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/connect.go:173:84: undefined: VARIANT
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/idispatch.go:26:90: undefined: VARIANT
../go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/idispatch.go:26:90: too many errors
```

**Comment by rubin55** [comment]
Just a heads-up that this issue will probably come up a bit more often as soon as Go 1.17 hits the streets (which has Windows on ARM support planned). I just tried compiling Syncthing from source and it chokes on this same issue.

**Comment by Jacalz** [comment]
I think this could have been fixed by https://github.com/go-ole/go-ole/commit/01a19da4520446eb65eb776e62ad6d43c56e775b?

**Comment by Erisa** [comment]
> 
> 
> I think this could have been fixed by [01a19da](https://github.com/go-ole/go-ole/commit/01a19da4520446eb65eb776e62ad6d43c56e775b)?

For 32-bit `windows/arm` it was indeed fixed there. The isssue still happens on the newly added `windows/arm64` and will need a similar fix, like #217

**Comment by Erisa** [comment]
@mattn this issue can be safely closed now too too, `windows/arm` was fixed by https://github.com/go-ole/go-ole/commit/01a19da4520446eb65eb776e62ad6d43c56e775b and `windows/arm64` was fixed by https://github.com/go-ole/go-ole/pull/223
